# ==============================================================================================
#   docker compose -f docker-compose.yml -f docker-compose.build.yml build
#   docker compose -f docker-compose.yml -f docker-compose.build.yml up -d
# ==============================================================================================

services:
  backend:
    build:
      context: ./backend
      target: runtime
      args:
        GIT_SHA: ${GIT_SHA:-}

  artist-images:
    build:
      context: ./backend
      target: tools

  lyrics:
    build:
      context: ./backend
      target: tools

  frontend:
    build:
      context: ./frontend
      args:
        GIT_SHA: ${GIT_SHA:-}
