-- Сырые события воспроизведения и свёрнутый из них профиль вкуса (TasteProfileConfiguration).

CREATE TABLE playback_events (
    id uuid NOT NULL,
    sequence bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id uuid NOT NULL,
    track_id uuid,
    entity_id uuid,
    type integer NOT NULL,
    occurred_at timestamp with time zone NOT NULL,
    position_seconds integer NOT NULL,
    listened_seconds integer NOT NULL,
    duration_seconds integer NOT NULL,
    session_id uuid NOT NULL,
    source integer NOT NULL,
    source_id uuid,
    platform character varying(32) NOT NULL,
    CONSTRAINT pk_playback_events PRIMARY KEY (id),
    CONSTRAINT fk_playback_events_tracks_track_id FOREIGN KEY (track_id) REFERENCES tracks (id) ON DELETE CASCADE,
    CONSTRAINT fk_playback_events_users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_playback_events_occurred_at ON playback_events (occurred_at);

CREATE INDEX ix_playback_events_session_id_occurred_at ON playback_events (session_id, occurred_at);

CREATE INDEX ix_playback_events_track_id ON playback_events (track_id);

CREATE INDEX ix_playback_events_user_id_occurred_at ON playback_events (user_id, occurred_at);

CREATE INDEX ix_playback_events_user_id_sequence ON playback_events (user_id, sequence);

CREATE INDEX ix_playback_events_user_id_track_id_occurred_at ON playback_events (user_id, track_id, occurred_at);

CREATE TABLE user_track_affinity (
    user_id uuid NOT NULL,
    track_id uuid NOT NULL,
    play_count integer NOT NULL,
    completed_count integer NOT NULL,
    skip_count integer NOT NULL,
    replay_count integer NOT NULL,
    playlist_adds integer NOT NULL,
    total_listened_seconds bigint NOT NULL,
    completion_sum double precision NOT NULL,
    completion_samples integer NOT NULL,
    decayed_weight double precision NOT NULL,
    decay_anchor timestamp with time zone NOT NULL,
    score double precision NOT NULL,
    first_played_at timestamp with time zone NOT NULL,
    last_played_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_user_track_affinity PRIMARY KEY (user_id, track_id),
    CONSTRAINT fk_user_track_affinity_tracks_track_id FOREIGN KEY (track_id) REFERENCES tracks (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_track_affinity_users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_user_track_affinity_track_id ON user_track_affinity (track_id);

CREATE INDEX ix_user_track_affinity_user_id_last_played_at ON user_track_affinity (user_id, last_played_at);

CREATE INDEX ix_user_track_affinity_user_id_score ON user_track_affinity (user_id, score);

CREATE TABLE user_artist_affinity (
    user_id uuid NOT NULL,
    artist_id uuid NOT NULL,
    play_count integer NOT NULL,
    skip_count integer NOT NULL,
    decayed_weight double precision NOT NULL,
    decay_anchor timestamp with time zone NOT NULL,
    score double precision NOT NULL,
    last_played_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_user_artist_affinity PRIMARY KEY (user_id, artist_id),
    CONSTRAINT fk_user_artist_affinity_artists_artist_id FOREIGN KEY (artist_id) REFERENCES artists (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_artist_affinity_users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_user_artist_affinity_artist_id ON user_artist_affinity (artist_id);

CREATE INDEX ix_user_artist_affinity_user_id_score ON user_artist_affinity (user_id, score);

CREATE TABLE user_genre_affinity (
    user_id uuid NOT NULL,
    genre_id uuid NOT NULL,
    play_count integer NOT NULL,
    skip_count integer NOT NULL,
    decayed_weight double precision NOT NULL,
    decay_anchor timestamp with time zone NOT NULL,
    score double precision NOT NULL,
    last_played_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_user_genre_affinity PRIMARY KEY (user_id, genre_id),
    CONSTRAINT fk_user_genre_affinity_genres_genre_id FOREIGN KEY (genre_id) REFERENCES genres (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_genre_affinity_users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_user_genre_affinity_genre_id ON user_genre_affinity (genre_id);

CREATE INDEX ix_user_genre_affinity_user_id_score ON user_genre_affinity (user_id, score);

CREATE TABLE user_taste_profiles (
    user_id uuid NOT NULL,
    positive_signal_count integer NOT NULL,
    positive_signal_mass double precision NOT NULL,
    signal_decay_anchor timestamp with time zone NOT NULL,
    total_event_count integer NOT NULL,
    average_completion double precision NOT NULL,
    skip_rate double precision NOT NULL,
    distinct_tracks integer NOT NULL,
    year_center double precision,
    year_spread double precision NOT NULL,
    top_artists jsonb NOT NULL,
    top_genres jsonb NOT NULL,
    dayparts jsonb NOT NULL,
    maturity integer NOT NULL,
    events_watermark bigint NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_user_taste_profiles PRIMARY KEY (user_id),
    CONSTRAINT fk_user_taste_profiles_users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE user_taste_vectors (
    user_id uuid NOT NULL,
    context integer NOT NULL,
    vector real[] NOT NULL,
    dimension integer NOT NULL,
    positive_count integer NOT NULL,
    negative_count integer NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_user_taste_vectors PRIMARY KEY (user_id, context),
    CONSTRAINT fk_user_taste_vectors_users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
