// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicStreaming.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MusicStreaming.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MusicStreaming.Application.Services.DailyActivityRow", b =>
                {
                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<long>("ListenedSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("listened_seconds");

                    b.Property<int>("Plays")
                        .HasColumnType("integer")
                        .HasColumnName("plays");

                    b.ToTable("daily_activity_row", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("MusicStreaming.Application.Services.HourlyActivityRow", b =>
                {
                    b.Property<int>("Hour")
                        .HasColumnType("integer")
                        .HasColumnName("hour");

                    b.Property<long>("ListenedSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("listened_seconds");

                    b.Property<int>("Plays")
                        .HasColumnType("integer")
                        .HasColumnName("plays");

                    b.ToTable("hourly_activity_row", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("MusicStreaming.Application.Services.LibraryStatsRow", b =>
                {
                    b.Property<int>("Albums")
                        .HasColumnType("integer")
                        .HasColumnName("albums");

                    b.Property<int>("Artists")
                        .HasColumnType("integer")
                        .HasColumnName("artists");

                    b.Property<long>("DurationSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_seconds");

                    b.Property<int>("Playlists")
                        .HasColumnType("integer")
                        .HasColumnName("playlists");

                    b.Property<long>("TotalBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("total_bytes");

                    b.Property<int>("Tracks")
                        .HasColumnType("integer")
                        .HasColumnName("tracks");

                    b.ToTable("library_stats_row", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });


            modelBuilder.Entity("MusicStreaming.Domain.Entities.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_id");

                    b.Property<string>("CoverPath")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("cover_path");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("NormalizedTitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("normalized_title");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_albums");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_albums_created_at");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_albums_title");

                    b.HasIndex("ArtistId", "NormalizedTitle")
                        .IsUnique()
                        .HasDatabaseName("ix_albums_artist_id_normalized_title");

                    b.ToTable("albums", (string)null);
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("image_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_artists");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_artists_name");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_artists_normalized_name");

                    b.ToTable("artists", (string)null);
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.Favorite", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("UserId", "TrackId")
                        .HasName("pk_favorites");

                    b.HasIndex("TrackId")
                        .HasDatabaseName("ix_favorites_track_id");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_favorites_user_id_created_at");

                    b.ToTable("favorites", (string)null);
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_genres");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_genres_normalized_name");

                    b.ToTable("genres", (string)null);
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.Integrations.LastfmAccount", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("ConnectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("connected_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<DateTimeOffset?>("LastScrobbleAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_scrobble_at");

                    b.Property<string>("SessionKey")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("session_key");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("pk_lastfm_accounts");

                    b.ToTable("lastfm_accounts", (string)null);
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.Integrations.OutboundJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("dedupe_key");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_outbound_jobs");

                    b.HasIndex("DedupeKey")
                        .IsUnique()
                        .HasDatabaseName("ix_outbound_jobs_dedupe_key");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_outbound_jobs_user_id");

                    b.HasIndex("State", "NextAttemptAt")
                        .HasDatabaseName("ix_outbound_jobs_state_next_attempt_at");

                    b.ToTable("outbound_jobs", (string)null);
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.ListeningHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("PlaybackPosition")
                        .HasColumnType("integer")
                        .HasColumnName("playback_position");

                    b.Property<DateTimeOffset>("PlayedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("played_at");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_listening_history");

                    b.HasIndex("PlayedAt")
                        .HasDatabaseName("ix_listening_history_played_at");

                    b.HasIndex("TrackId")
                        .HasDatabaseName("ix_listening_history_track_id");

                    b.HasIndex("UserId", "PlayedAt")
                        .HasDatabaseName("ix_listening_history_user_id_played_at");

                    b.HasIndex("UserId", "TrackId", "PlayedAt")
                        .HasDatabaseName("ix_listening_history_user_id_track_id_played_at");

                    b.ToTable("listening_history", (string)null);
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.ListeningStat", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("Hour")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hour");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<long>("ListenedSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("listened_seconds");

                    b.Property<int>("PlayCount")
                        .HasColumnType("integer")
                        .HasColumnName("play_count");

                    b.HasKey("UserId", "Hour", "TrackId")
                        .HasName("pk_listening_stats");

                    b.HasIndex("TrackId")
                        .HasDatabaseName("ix_listening_stats_track_id");

                    b.ToTable("listening_stats", (string)null);
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.Playlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CoverPath")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("cover_path");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_playlists");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_playlists_created_at");

                    b.HasIndex("IsPublic", "UpdatedAt")
                        .HasDatabaseName("ix_playlists_is_public_updated_at");

                    b.HasIndex("UserId", "Name")
                        .HasDatabaseName("ix_playlists_user_id_name");

                    b.ToTable("playlists", (string)null);
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.PlaylistTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("uuid")
                        .HasColumnName("playlist_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.HasKey("Id")
                        .HasName("pk_playlist_tracks");

                    b.HasIndex("TrackId")
                        .HasDatabaseName("ix_playlist_tracks_track_id");

                    b.HasIndex("PlaylistId", "Position")
                        .HasDatabaseName("ix_playlist_tracks_playlist_id_position");

                    b.HasIndex("PlaylistId", "TrackId")
                        .IsUnique()
                        .HasDatabaseName("ix_playlist_tracks_playlist_id_track_id");

                    b.ToTable("playlist_tracks", (string)null);
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.Recommendations.PlaybackEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<int>("ListenedSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("listened_seconds");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("platform");

                    b.Property<int>("PositionSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("position_seconds");

                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Sequence"));

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<Guid?>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_playback_events");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_playback_events_occurred_at");

                    b.HasIndex("TrackId")
                        .HasDatabaseName("ix_playback_events_track_id");

                    b.HasIndex("SessionId", "OccurredAt")
                        .HasDatabaseName("ix_playback_events_session_id_occurred_at");

                    b.HasIndex("UserId", "OccurredAt")
                        .HasDatabaseName("ix_playback_events_user_id_occurred_at");

                    b.HasIndex("UserId", "Sequence")
                        .HasDatabaseName("ix_playback_events_user_id_sequence");

                    b.HasIndex("UserId", "TrackId", "OccurredAt")
                        .HasDatabaseName("ix_playback_events_user_id_track_id_occurred_at");

                    b.ToTable("playback_events", (string)null);
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.Recommendations.RecommendationCacheEntry", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("ShelfKey")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("shelf_key");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.HasKey("UserId", "ShelfKey")
                        .HasName("pk_recommendation_cache");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_recommendation_cache_expires_at");

                    b.HasIndex("UserId", "Position")
                        .HasDatabaseName("ix_recommendation_cache_user_id_position");

                    b.ToTable("recommendation_cache", (string)null);
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.Recommendations.RecommendationImpression", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ClickedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("clicked_at");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("ShelfKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("shelf_key");

                    b.Property<DateTimeOffset>("ShownAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("shown_at");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_recommendation_impressions");

                    b.HasIndex("ShownAt")
                        .HasDatabaseName("ix_recommendation_impressions_shown_at");

                    b.HasIndex("TrackId")
                        .HasDatabaseName("ix_recommendation_impressions_track_id");

                    b.HasIndex("UserId", "ShelfKey", "ShownAt")
                        .HasDatabaseName("ix_recommendation_impressions_user_id_shelf_key_shown_at");

                    b.HasIndex("UserId", "TrackId", "ShownAt")
                        .HasDatabaseName("ix_recommendation_impressions_user_id_track_id_shown_at");

                    b.ToTable("recommendation_impressions", (string)null);
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.Recommendations.RecommendationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CandidateCount")
                        .HasColumnType("integer")
                        .HasColumnName("candidate_count");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error");

                    b.Property<int>("ShelfCount")
                        .HasColumnType("integer")
                        .HasColumnName("shelf_count");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Trigger")
                        .HasColumnType("integer")
                        .HasColumnName("trigger");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_recommendation_runs");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_recommendation_runs_started_at");

                    b.HasIndex("UserId", "StartedAt")
                        .HasDatabaseName("ix_recommendation_runs_user_id_started_at");

                    b.ToTable("recommendation_runs", (string)null);
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.Recommendations.TrackAudioFeatures", b =>
                {
                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<int>("AlgorithmVersion")
                        .HasColumnType("integer")
                        .HasColumnName("algorithm_version");

                    b.Property<DateTimeOffset>("AnalyzedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("analyzed_at");

                    b.Property<double>("AnalyzedSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("analyzed_seconds");

                    b.Property<double>("Brightness")
                        .HasColumnType("double precision")
                        .HasColumnName("brightness");

                    b.Property<double>("DynamicRangeDb")
                        .HasColumnType("double precision")
                        .HasColumnName("dynamic_range_db");

                    b.Property<double>("Energy")
                        .HasColumnType("double precision")
                        .HasColumnName("energy");

                    b.Property<string>("Error")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("error");

                    b.Property<double>("LoudnessDb")
                        .HasColumnType("double precision")
                        .HasColumnName("loudness_db");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("boolean")
                        .HasColumnName("succeeded");

                    b.Property<double?>("TempoBpm")
                        .HasColumnType("double precision")
                        .HasColumnName("tempo_bpm");

                    b.Property<double>("TempoConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("tempo_confidence");

                    b.HasKey("TrackId")
                        .HasName("pk_track_audio_features");

                    b.HasIndex("AnalyzedAt")
                        .HasDatabaseName("ix_track_audio_features_analyzed_at");

                    b.HasIndex("Succeeded", "AlgorithmVersion")
                        .HasDatabaseName("ix_track_audio_features_succeeded_algorithm_version");

                    b.ToTable("track_audio_features", (string)null);
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.Recommendations.TrackSimilarity", b =>
                {
                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<Guid>("SimilarTrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("similar_track_id");

                    b.Property<double?>("AudioScore")
                        .HasColumnType("double precision")
                        .HasColumnName("audio_score");

                    b.Property<double>("CollabScore")
                        .HasColumnType("double precision")
                        .HasColumnName("collab_score");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<double>("ContentScore")
                        .HasColumnType("double precision")
                        .HasColumnName("content_score");

                    b.Property<double>("Score")
                        .HasColumnType("double precision")
                        .HasColumnName("score");

                    b.Property<int>("Support")
                        .HasColumnType("integer")
                        .HasColumnName("support");

                    b.HasKey("TrackId", "SimilarTrackId")
                        .HasName("pk_track_similarity");

                    b.HasIndex("SimilarTrackId")
                        .HasDatabaseName("ix_track_similarity_similar_track_id");

                    b.HasIndex("TrackId", "Score")
                        .HasDatabaseName("ix_track_similarity_track_id_score");

                    b.ToTable("track_similarity", (string)null);
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.Recommendations.TrackStats", b =>
                {
                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<double>("CompletionRate")
                        .HasColumnType("double precision")
                        .HasColumnName("completion_rate");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<int>("DistinctListeners")
                        .HasColumnType("integer")
                        .HasColumnName("distinct_listeners");

                    b.Property<DateTimeOffset?>("LastPlayedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_played_at");

                    b.Property<int>("PlayCount")
                        .HasColumnType("integer")
                        .HasColumnName("play_count");

                    b.Property<int>("PlayCount30d")
                        .HasColumnType("integer")
                        .HasColumnName("play_count30d");

                    b.Property<double>("PopularityScore")
                        .HasColumnType("double precision")
                        .HasColumnName("popularity_score");

                    b.Property<int>("SkipCount")
                        .HasColumnType("integer")
                        .HasColumnName("skip_count");

                    b.Property<double>("SkipRate")
                        .HasColumnType("double precision")
                        .HasColumnName("skip_rate");

                    b.HasKey("TrackId")
                        .HasName("pk_track_stats");

                    b.HasIndex("PopularityScore")
                        .HasDatabaseName("ix_track_stats_popularity_score");

                    b.ToTable("track_stats", (string)null);
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.Recommendations.UserArtistAffinity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_id");

                    b.Property<DateTimeOffset>("DecayAnchor")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decay_anchor");

                    b.Property<double>("DecayedWeight")
                        .HasColumnType("double precision")
                        .HasColumnName("decayed_weight");

                    b.Property<DateTimeOffset>("LastPlayedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_played_at");

                    b.Property<int>("PlayCount")
                        .HasColumnType("integer")
                        .HasColumnName("play_count");

                    b.Property<double>("Score")
                        .HasColumnType("double precision")
                        .HasColumnName("score");

                    b.Property<int>("SkipCount")
                        .HasColumnType("integer")
                        .HasColumnName("skip_count");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId", "ArtistId")
                        .HasName("pk_user_artist_affinity");

                    b.HasIndex("ArtistId")
                        .HasDatabaseName("ix_user_artist_affinity_artist_id");

                    b.HasIndex("UserId", "Score")
                        .HasDatabaseName("ix_user_artist_affinity_user_id_score");

                    b.ToTable("user_artist_affinity", (string)null);
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.Recommendations.UserGenreAffinity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uuid")
                        .HasColumnName("genre_id");

                    b.Property<DateTimeOffset>("DecayAnchor")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decay_anchor");

                    b.Property<double>("DecayedWeight")
                        .HasColumnType("double precision")
                        .HasColumnName("decayed_weight");

                    b.Property<DateTimeOffset>("LastPlayedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_played_at");

                    b.Property<int>("PlayCount")
                        .HasColumnType("integer")
                        .HasColumnName("play_count");

                    b.Property<double>("Score")
                        .HasColumnType("double precision")
                        .HasColumnName("score");

                    b.Property<int>("SkipCount")
                        .HasColumnType("integer")
                        .HasColumnName("skip_count");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId", "GenreId")
                        .HasName("pk_user_genre_affinity");

                    b.HasIndex("GenreId")
                        .HasDatabaseName("ix_user_genre_affinity_genre_id");

                    b.HasIndex("UserId", "Score")
                        .HasDatabaseName("ix_user_genre_affinity_user_id_score");

                    b.ToTable("user_genre_affinity", (string)null);
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.Recommendations.UserTasteProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<double>("AverageCompletion")
                        .HasColumnType("double precision")
                        .HasColumnName("average_completion");

                    b.Property<int>("DistinctArtists")
                        .HasColumnType("integer")
                        .HasColumnName("distinct_artists");

                    b.Property<int>("DistinctTracks")
                        .HasColumnType("integer")
                        .HasColumnName("distinct_tracks");

                    b.Property<long>("EventsWatermark")
                        .HasColumnType("bigint")
                        .HasColumnName("events_watermark");

                    b.Property<int>("Maturity")
                        .HasColumnType("integer")
                        .HasColumnName("maturity");

                    b.Property<int>("PositiveSignalCount")
                        .HasColumnType("integer")
                        .HasColumnName("positive_signal_count");

                    b.Property<double>("SkipRate")
                        .HasColumnType("double precision")
                        .HasColumnName("skip_rate");

                    b.Property<string>("TopArtists")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("top_artists");

                    b.Property<string>("TopGenres")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("top_genres");

                    b.Property<int>("TotalEventCount")
                        .HasColumnType("integer")
                        .HasColumnName("total_event_count");

                    b.Property<long>("TotalListeningSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("total_listening_seconds");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<double?>("YearCenter")
                        .HasColumnType("double precision")
                        .HasColumnName("year_center");

                    b.Property<double>("YearSpread")
                        .HasColumnType("double precision")
                        .HasColumnName("year_spread");

                    b.HasKey("UserId")
                        .HasName("pk_user_taste_profiles");

                    b.ToTable("user_taste_profiles", (string)null);
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.Recommendations.UserTrackAffinity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<int>("CompletedCount")
                        .HasColumnType("integer")
                        .HasColumnName("completed_count");

                    b.Property<int>("CompletionSamples")
                        .HasColumnType("integer")
                        .HasColumnName("completion_samples");

                    b.Property<double>("CompletionSum")
                        .HasColumnType("double precision")
                        .HasColumnName("completion_sum");

                    b.Property<DateTimeOffset>("DecayAnchor")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decay_anchor");

                    b.Property<double>("DecayedWeight")
                        .HasColumnType("double precision")
                        .HasColumnName("decayed_weight");

                    b.Property<DateTimeOffset>("FirstPlayedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_played_at");

                    b.Property<DateTimeOffset>("LastPlayedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_played_at");

                    b.Property<int>("PlayCount")
                        .HasColumnType("integer")
                        .HasColumnName("play_count");

                    b.Property<int>("PlaylistAdds")
                        .HasColumnType("integer")
                        .HasColumnName("playlist_adds");

                    b.Property<int>("QueueAdds")
                        .HasColumnType("integer")
                        .HasColumnName("queue_adds");

                    b.Property<int>("ReplayCount")
                        .HasColumnType("integer")
                        .HasColumnName("replay_count");

                    b.Property<double>("Score")
                        .HasColumnType("double precision")
                        .HasColumnName("score");

                    b.Property<int>("SkipCount")
                        .HasColumnType("integer")
                        .HasColumnName("skip_count");

                    b.Property<long>("TotalListenedSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("total_listened_seconds");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId", "TrackId")
                        .HasName("pk_user_track_affinity");

                    b.HasIndex("TrackId")
                        .HasDatabaseName("ix_user_track_affinity_track_id");

                    b.HasIndex("UserId", "LastPlayedAt")
                        .HasDatabaseName("ix_user_track_affinity_user_id_last_played_at");

                    b.HasIndex("UserId", "Score")
                        .HasDatabaseName("ix_user_track_affinity_user_id_score");

                    b.ToTable("user_track_affinity", (string)null);
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AlbumId")
                        .HasColumnType("uuid")
                        .HasColumnName("album_id");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_id");

                    b.Property<int?>("BitrateKbps")
                        .HasColumnType("integer")
                        .HasColumnName("bitrate_kbps");

                    b.Property<int?>("BitsPerSample")
                        .HasColumnType("integer")
                        .HasColumnName("bits_per_sample");

                    b.Property<string>("Codec")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("codec");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DiscNumber")
                        .HasColumnType("integer")
                        .HasColumnName("disc_number");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("file_path");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<Guid?>("GenreId")
                        .HasColumnType("uuid")
                        .HasColumnName("genre_id");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mime_type");

                    b.Property<string>("NormalizedTitle")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("normalized_title");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("original_file_name");

                    b.Property<int?>("SampleRateHz")
                        .HasColumnType("integer")
                        .HasColumnName("sample_rate_hz");

                    b.Property<double>("ShuffleKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasColumnName("shuffle_key")
                        .HasDefaultValueSql("random()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("title");

                    b.Property<int?>("TrackNumber")
                        .HasColumnType("integer")
                        .HasColumnName("track_number");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_tracks");

                    b.HasIndex("AlbumId")
                        .HasDatabaseName("ix_tracks_album_id");

                    b.HasIndex("ArtistId")
                        .HasDatabaseName("ix_tracks_artist_id");

                    b.HasIndex("ContentHash")
                        .IsUnique()
                        .HasDatabaseName("ix_tracks_content_hash");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_tracks_created_at");

                    b.HasIndex("FilePath")
                        .IsUnique()
                        .HasDatabaseName("ix_tracks_file_path");

                    b.HasIndex("GenreId")
                        .HasDatabaseName("ix_tracks_genre_id");

                    b.HasIndex("ShuffleKey")
                        .HasDatabaseName("ix_tracks_shuffle_key");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_tracks_title");

                    b.ToTable("tracks", (string)null);
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.TrackArtist", b =>
                {
                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("TrackId", "ArtistId")
                        .HasName("pk_track_artists");

                    b.HasIndex("ArtistId")
                        .HasDatabaseName("ix_track_artists_artist_id");

                    b.HasIndex("TrackId", "Position")
                        .HasDatabaseName("ix_track_artists_track_id_position");

                    b.ToTable("track_artists", (string)null);
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.TrackLyrics", b =>
                {
                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<string>("Plain")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("text")
                        .HasColumnName("plain");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<string>("Synced")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("synced");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TrackId")
                        .HasName("pk_track_lyrics");

                    b.ToTable("track_lyrics", (string)null);
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_admin");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.UserSettings", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("Autoplay")
                        .HasColumnType("boolean")
                        .HasColumnName("autoplay");

                    b.Property<bool>("DataSaver")
                        .HasColumnType("boolean")
                        .HasColumnName("data_saver");

                    b.Property<int>("Quality")
                        .HasColumnType("integer")
                        .HasColumnName("quality");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("pk_user_settings");

                    b.ToTable("user_settings", (string)null);
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.Album", b =>
                {
                    b.HasOne("MusicStreaming.Domain.Entities.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_albums_artists_artist_id");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.Favorite", b =>
                {
                    b.HasOne("MusicStreaming.Domain.Entities.Track", "Track")
                        .WithMany("Favorites")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_favorites_tracks_track_id");

                    b.HasOne("MusicStreaming.Domain.Entities.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_favorites_users_user_id");

                    b.Navigation("Track");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.Integrations.LastfmAccount", b =>
                {
                    b.HasOne("MusicStreaming.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lastfm_accounts_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.Integrations.OutboundJob", b =>
                {
                    b.HasOne("MusicStreaming.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_outbound_jobs_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.ListeningHistoryEntry", b =>
                {
                    b.HasOne("MusicStreaming.Domain.Entities.Track", "Track")
                        .WithMany("History")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_listening_history_tracks_track_id");

                    b.HasOne("MusicStreaming.Domain.Entities.User", "User")
                        .WithMany("History")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_listening_history_users_user_id");

                    b.Navigation("Track");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.ListeningStat", b =>
                {
                    b.HasOne("MusicStreaming.Domain.Entities.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_listening_stats_tracks_track_id");

                    b.HasOne("MusicStreaming.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_listening_stats_users_user_id");

                    b.Navigation("Track");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.Playlist", b =>
                {
                    b.HasOne("MusicStreaming.Domain.Entities.User", "User")
                        .WithMany("Playlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_playlists_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.PlaylistTrack", b =>
                {
                    b.HasOne("MusicStreaming.Domain.Entities.Playlist", "Playlist")
                        .WithMany("Tracks")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_playlist_tracks_playlists_playlist_id");

                    b.HasOne("MusicStreaming.Domain.Entities.Track", "Track")
                        .WithMany("PlaylistTracks")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_playlist_tracks_tracks_track_id");

                    b.Navigation("Playlist");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.Recommendations.PlaybackEvent", b =>
                {
                    b.HasOne("MusicStreaming.Domain.Entities.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_playback_events_tracks_track_id");

                    b.HasOne("MusicStreaming.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_playback_events_users_user_id");

                    b.Navigation("Track");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.Recommendations.RecommendationCacheEntry", b =>
                {
                    b.HasOne("MusicStreaming.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recommendation_cache_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.Recommendations.RecommendationImpression", b =>
                {
                    b.HasOne("MusicStreaming.Domain.Entities.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recommendation_impressions_tracks_track_id");

                    b.HasOne("MusicStreaming.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recommendation_impressions_users_user_id");

                    b.Navigation("Track");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.Recommendations.TrackAudioFeatures", b =>
                {
                    b.HasOne("MusicStreaming.Domain.Entities.Track", "Track")
                        .WithOne("AudioFeatures")
                        .HasForeignKey("MusicStreaming.Domain.Entities.Recommendations.TrackAudioFeatures", "TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_track_audio_features_tracks_track_id");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.Recommendations.TrackSimilarity", b =>
                {
                    b.HasOne("MusicStreaming.Domain.Entities.Track", "SimilarTrack")
                        .WithMany()
                        .HasForeignKey("SimilarTrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_track_similarity_tracks_similar_track_id");

                    b.HasOne("MusicStreaming.Domain.Entities.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_track_similarity_tracks_track_id");

                    b.Navigation("SimilarTrack");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.Recommendations.TrackStats", b =>
                {
                    b.HasOne("MusicStreaming.Domain.Entities.Track", "Track")
                        .WithOne("Stats")
                        .HasForeignKey("MusicStreaming.Domain.Entities.Recommendations.TrackStats", "TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_track_stats_tracks_track_id");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.Recommendations.UserArtistAffinity", b =>
                {
                    b.HasOne("MusicStreaming.Domain.Entities.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_artist_affinity_artists_artist_id");

                    b.HasOne("MusicStreaming.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_artist_affinity_users_user_id");

                    b.Navigation("Artist");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.Recommendations.UserGenreAffinity", b =>
                {
                    b.HasOne("MusicStreaming.Domain.Entities.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_genre_affinity_genres_genre_id");

                    b.HasOne("MusicStreaming.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_genre_affinity_users_user_id");

                    b.Navigation("Genre");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.Recommendations.UserTasteProfile", b =>
                {
                    b.HasOne("MusicStreaming.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_taste_profiles_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.Recommendations.UserTrackAffinity", b =>
                {
                    b.HasOne("MusicStreaming.Domain.Entities.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_track_affinity_tracks_track_id");

                    b.HasOne("MusicStreaming.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_track_affinity_users_user_id");

                    b.Navigation("Track");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("MusicStreaming.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.Track", b =>
                {
                    b.HasOne("MusicStreaming.Domain.Entities.Album", "Album")
                        .WithMany("Tracks")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tracks_albums_album_id");

                    b.HasOne("MusicStreaming.Domain.Entities.Artist", "Artist")
                        .WithMany("Tracks")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tracks_artists_artist_id");

                    b.HasOne("MusicStreaming.Domain.Entities.Genre", "Genre")
                        .WithMany("Tracks")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tracks_genres_genre_id");

                    b.Navigation("Album");

                    b.Navigation("Artist");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.TrackArtist", b =>
                {
                    b.HasOne("MusicStreaming.Domain.Entities.Artist", "Artist")
                        .WithMany("TrackCredits")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_track_artists_artists_artist_id");

                    b.HasOne("MusicStreaming.Domain.Entities.Track", "Track")
                        .WithMany("TrackArtists")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_track_artists_tracks_track_id");

                    b.Navigation("Artist");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.TrackLyrics", b =>
                {
                    b.HasOne("MusicStreaming.Domain.Entities.Track", "Track")
                        .WithOne("Lyrics")
                        .HasForeignKey("MusicStreaming.Domain.Entities.TrackLyrics", "TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_track_lyrics_tracks_track_id");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.UserSettings", b =>
                {
                    b.HasOne("MusicStreaming.Domain.Entities.User", "User")
                        .WithOne("Settings")
                        .HasForeignKey("MusicStreaming.Domain.Entities.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_settings_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.Album", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.Artist", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("TrackCredits");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.Genre", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.Playlist", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.Track", b =>
                {
                    b.Navigation("AudioFeatures");

                    b.Navigation("Favorites");

                    b.Navigation("History");

                    b.Navigation("Lyrics");

                    b.Navigation("PlaylistTracks");

                    b.Navigation("Stats");

                    b.Navigation("TrackArtists");
                });

            modelBuilder.Entity("MusicStreaming.Domain.Entities.User", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("History");

                    b.Navigation("Playlists");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
